<?php

namespace AppBundle\Repository;

use Symfony\Component\Locale\Locale;

/**
 * TicketTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTypeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLikeQueryBuilder($filter)
	{ 
		return $this
		->createQueryBuilder('tt')
		->where('tt.conditions = :filter')
		->setParameter('filter', $filter)
		;
	}  
}
