services:
    app_louvre.ticket.age:
        class: AppBundle\Services\Ticket\Age
    app_louvre.booking.code:
        class: AppBundle\Services\Booking\Code
        arguments: ['@doctrine.orm.entity_manager']
    app_louvre.booking.token:
        class: AppBundle\Services\Booking\Token
        arguments: ['@doctrine.orm.entity_manager']
    app_louvre.ticket.price:
        class: AppBundle\Services\Ticket\Price
        arguments: ['@doctrine.orm.entity_manager']
    app_louvre.booking.prices:
        class: AppBundle\Services\Booking\Prices
        arguments: ['@doctrine.orm.entity_manager','@app_louvre.ticket.price','@app_louvre.ticket.age']
    app_louvre.validator.notholidays:                         
        class: AppBundle\Validators\Booking\NotHolidaysValidator
        tags:
            - { name: validator.constraint_validator, alias: app_louvre_notholidays }
    app_louvre.validator.notuesday:
        class: AppBundle\Validators\Booking\NotTuesdayValidator
        tags:
            - { name: validator.constraint_validator, alias: app_louvre_nottuesday }
    app_louvre.validator.notsunday:
        class: AppBundle\Validators\Booking\NotSundayValidator
        tags:
            - { name: validator.constraint_validator, alias: app_louvre_notsunday }
    app_louvre.validator.notpreviousday:                         
        class: AppBundle\Validators\Booking\NotPreviousDayValidator
        tags:
            - { name: validator.constraint_validator, alias: app_louvre_notpreviousday }
    app_louvre.validator.notafterhours:                         
        class: AppBundle\Validators\Booking\NotAfterHoursValidator
        tags:
            - { name: validator.constraint_validator, alias: app_louvre_notafterhours }
    app_louvre.validator.notmorethousand:                         
        class: AppBundle\Validators\Booking\NotMoreThousandValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: app_louvre_notmorethousand }
    app_louvre.mailer:
        class: AppBundle\Services\Mailer\NotificationMailer
        arguments: ['@mailer','@templating']